import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:livestock/features/auth/presentation/providers/auth_providers.dart';
import 'package:livestock/features/farmer_management/domain/entities/farmer.dart';
import 'package:livestock/features/farmer_management/presentation/providers/farmer_registration_state_provider.dart';
import 'package:livestock/features/farmer_management/presentation/widgets/farmer_info_step.dart';
import 'package:livestock/features/farmer_management/presentation/widgets/farmer_location_step.dart';
import 'package:livestock/features/farmer_management/presentation/widgets/farmer_access_step.dart';

/// Screen for registering a new farmer
class FarmerRegistrationScreen extends ConsumerStatefulWidget {
  const FarmerRegistrationScreen({super.key});

  @override
  ConsumerState<FarmerRegistrationScreen> createState() =>
      _FarmerRegistrationScreenState();
}

class _FarmerRegistrationScreenState
    extends ConsumerState<FarmerRegistrationScreen> {
  final _formKey = GlobalKey<FormState>();

  // Form fields
  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
  final _emailController = TextEditingController();
  final _nationalIdController = TextEditingController();
  final _locationController = TextEditingController();
  final _totalCattleController = TextEditingController(text: '0');
  final _lactatingCattleController = TextEditingController(text: '0');
  bool _hasAppAccess = false;

  @override
  void dispose() {
    _nameController.dispose();
    _phoneController.dispose();
    _emailController.dispose();
    _nationalIdController.dispose();
    _locationController.dispose();
    _totalCattleController.dispose();
    _lactatingCattleController.dispose();
    super.dispose();
  }

  void _handleSubmit() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    final user = ref.read(currentAuthUserProvider);

    if (user == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('User not authenticated')),
      );
      return;
    }

    // Create farmer entity
    // Extract first name and surname from name field for backward compatibility
    final fullName = _nameController.text.trim();
    final nameParts = fullName.split(' ');
    final firstName = nameParts.isNotEmpty ? nameParts.first : fullName;
    final surname = nameParts.length > 1 ? nameParts.last : fullName;
    
    final farmer = Farmer(
      id: '', // Will be generated by Firestore
      name: fullName,
      phoneNumber: _phoneController.text.trim(),
      email: _emailController.text.trim().isEmpty
          ? null
          : _emailController.text.trim(),
      nationalId: _nationalIdController.text.trim(),
      location: _locationController.text.trim(),
      cooperativeId: user.cooperativeId ?? '',
      hasAppAccess: _hasAppAccess,
      creditScore: 50.0, // Initial score
      totalCattle: int.tryParse(_totalCattleController.text) ?? 0,
      lactatingCattle: int.tryParse(_lactatingCattleController.text) ?? 0,
      registeredAt: DateTime.now(),
      firstName: firstName,
      surname: surname,
    );

    await ref
        .read(farmerRegistrationProvider.notifier)
        .registerFarmer(farmer);

    final state = ref.read(farmerRegistrationProvider);

    if (state.registeredFarmer != null && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            'Farmer registered successfully! ID: ${state.registeredFarmer!.id}',
          ),
          backgroundColor: Colors.green,
        ),
      );

      // Navigate back or reset form
      Navigator.of(context).pop(state.registeredFarmer);
    } else if (state.errorMessage != null && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(state.errorMessage!),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(farmerRegistrationProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Register New Farmer'),
        elevation: 0,
        centerTitle: true,
      ),
      body: Form(
        key: _formKey,
        child: Stepper(
          type: StepperType.horizontal,
          currentStep: state.currentStep,
          controlsBuilder: (context, details) {
            return Padding(
              padding: const EdgeInsets.only(top: 24),
              child: Row(
                children: [
                  if (details.currentStep > 0)
                    Expanded(
                      child: OutlinedButton.icon(
                        onPressed: details.onStepCancel,
                        icon: const Icon(Icons.arrow_back),
                        label: const Text('Back'),
                        style: OutlinedButton.styleFrom(
                          padding: const EdgeInsets.symmetric(vertical: 16),
                        ),
                      ),
                    ),
                  if (details.currentStep > 0) const SizedBox(width: 12),
                  Expanded(
                    flex: 2,
                    child: ElevatedButton.icon(
                      onPressed: state.isLoading ? null : details.onStepContinue,
                      icon: state.isLoading
                          ? const SizedBox(
                              width: 20,
                              height: 20,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                color: Colors.white,
                              ),
                            )
                          : Icon(
                              details.currentStep < 2
                                  ? Icons.arrow_forward
                                  : Icons.check,
                            ),
                      label: Text(
                        details.currentStep < 2 ? 'Continue' : 'Register Farmer',
                      ),
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        backgroundColor: Colors.green,
                      ),
                    ),
                  ),
                ],
              ),
            );
          },
          onStepContinue: () {
            if (state.currentStep < 2) {
              if (_formKey.currentState!.validate()) {
                ref.read(farmerRegistrationProvider.notifier).nextStep();
              }
            } else {
              _handleSubmit();
            }
          },
          onStepCancel: () {
            if (state.currentStep > 0) {
              ref.read(farmerRegistrationProvider.notifier).previousStep();
            } else {
              Navigator.of(context).pop();
            }
          },
          steps: [
            Step(
              title: const Text('Personal Information'),
              content: FarmerInfoStep(
                nameController: _nameController,
                phoneController: _phoneController,
                emailController: _emailController,
                nationalIdController: _nationalIdController,
              ),
              isActive: state.currentStep >= 0,
              state: state.currentStep > 0
                  ? StepState.complete
                  : StepState.indexed,
            ),
            Step(
              title: const Text('Location & Cattle'),
              content: FarmerLocationStep(
                locationController: _locationController,
                totalCattleController: _totalCattleController,
                lactatingCattleController: _lactatingCattleController,
              ),
              isActive: state.currentStep >= 1,
              state: state.currentStep > 1
                  ? StepState.complete
                  : StepState.indexed,
            ),
            Step(
              title: const Text('App Access'),
              content: FarmerAccessStep(
                hasAppAccess: _hasAppAccess,
                onChanged: (value) {
                  setState(() {
                    _hasAppAccess = value;
                  });
                },
              ),
              isActive: state.currentStep >= 2,
            ),
          ],
        ),
      ),
    );
  }
}
