import 'package:cloud_firestore/cloud_firestore.dart';
import '../../../../core/errors/failures.dart';
import '../../../../core/utils/result.dart';
import '../../domain/entities/loan.dart';
import '../../domain/entities/loan_repayment.dart';
import '../../domain/repositories/loan_repository.dart';
import '../datasources/loan_remote_datasource.dart';
import '../models/loan_model.dart';

/// Implementation of LoanRepository
class LoanRepositoryImpl implements LoanRepository {
  final LoanRemoteDataSource remoteDataSource;

  LoanRepositoryImpl({required this.remoteDataSource});

  @override
  Future<Result<Loan>> applyForLoan({
    required String farmerId,
    required String cooperativeId,
    required double principalAmount,
    required double interestRate,
    required int termMonths,
    required String mfiPartnerId,
  }) async {
    try {
      final now = DateTime.now();
      final disbursementDate = now;
      final nextPaymentDue = now.add(Duration(days: 30));

      final loanModel = LoanModel(
        id: '', // Will be generated by Firestore
        farmerId: farmerId,
        cooperativeId: cooperativeId,
        lendingModel: 'direct',
        loanType: 'input_loan',
        principalAmount: principalAmount,
        interestRate: interestRate,
        interestType: 'flat',
        termMonths: termMonths,
        outstandingBalance: principalAmount,
        disbursementDate: Timestamp.fromDate(disbursementDate),
        nextPaymentDue: Timestamp.fromDate(nextPaymentDue),
        status: 'pending',
        mfiPartnerId: mfiPartnerId,
        insuranceVerified: false, // Will be verified by Cloud Function
        createdAt: Timestamp.fromDate(now),
      );

      final createdLoan = await remoteDataSource.createLoan(loanModel);
      return Success(createdLoan.toEntity());
    } catch (e) {
      return Error(ServerFailure('Failed to apply for loan: $e'));
    }
  }

  @override
  Future<Result<Loan>> getLoanById(String loanId) async {
    try {
      // Note: This is a simplified implementation
      // In production, we'd need cooperativeId and farmerId
      throw UnimplementedError('Need cooperativeId and farmerId');
    } catch (e) {
      return Error(ServerFailure('Failed to get loan: $e'));
    }
  }

  @override
  Future<Result<List<Loan>>> getFarmerLoans(String farmerId) async {
    try {
      // Note: This is a simplified implementation
      // In production, we'd need cooperativeId
      throw UnimplementedError('Need cooperativeId');
    } catch (e) {
      return Error(ServerFailure('Failed to get farmer loans: $e'));
    }
  }

  @override
  Future<Result<List<Loan>>> getCooperativeLoans(String cooperativeId) async {
    try {
      final loans = await remoteDataSource.getCooperativeLoans(cooperativeId);
      return Success(loans.map((model) => model.toEntity()).toList());
    } catch (e) {
      return Error(ServerFailure('Failed to get cooperative loans: $e'));
    }
  }

  @override
  Future<Result<List<Loan>>> getPendingLoans(String cooperativeId) async {
    try {
      final loans = await remoteDataSource.getPendingLoans(cooperativeId);
      return Success(loans.map((model) => model.toEntity()).toList());
    } catch (e) {
      return Error(ServerFailure('Failed to get pending loans: $e'));
    }
  }

  @override
  Future<Result<Loan>> approveLoan(String loanId) async {
    try {
      // Note: This is a simplified implementation
      throw UnimplementedError('Need cooperativeId and farmerId');
    } catch (e) {
      return Error(ServerFailure('Failed to approve loan: $e'));
    }
  }

  @override
  Future<Result<Loan>> rejectLoan(String loanId, String reason) async {
    try {
      // Note: This is a simplified implementation
      throw UnimplementedError('Need cooperativeId and farmerId');
    } catch (e) {
      return Error(ServerFailure('Failed to reject loan: $e'));
    }
  }

  @override
  Future<Result<Loan>> disburseLoan(String loanId) async {
    try {
      // Note: This is a simplified implementation
      throw UnimplementedError('Need cooperativeId and farmerId');
    } catch (e) {
      return Error(ServerFailure('Failed to disburse loan: $e'));
    }
  }

  @override
  Future<Result<LoanRepayment>> processRepayment({
    required String loanId,
    required double amount,
    required double principalPaid,
    required double interestPaid,
    required PaymentMethod paymentMethod,
    String? milkDeliveryId,
  }) async {
    try {
      // Note: This is a simplified implementation
      throw UnimplementedError('Need cooperativeId and farmerId');
    } catch (e) {
      return Error(ServerFailure('Failed to process repayment: $e'));
    }
  }

  @override
  Future<Result<List<LoanRepayment>>> getLoanRepayments(String loanId) async {
    try {
      // Note: This is a simplified implementation
      throw UnimplementedError('Need cooperativeId and farmerId');
    } catch (e) {
      return Error(ServerFailure('Failed to get loan repayments: $e'));
    }
  }

  @override
  Future<Result<Loan>> updateLoanStatus(String loanId, LoanStatus status) async {
    try {
      // Note: This is a simplified implementation
      throw UnimplementedError('Need cooperativeId and farmerId');
    } catch (e) {
      return Error(ServerFailure('Failed to update loan status: $e'));
    }
  }

  @override
  Stream<List<Loan>> watchFarmerLoans(String farmerId) {
    // Note: This is a simplified implementation
    throw UnimplementedError('Need cooperativeId');
  }

  @override
  Stream<List<Loan>> watchCooperativeLoans(String cooperativeId) {
    return remoteDataSource
        .watchCooperativeLoans(cooperativeId)
        .map((models) => models.map((model) => model.toEntity()).toList());
  }
}
