// Mocks generated by Mockito 5.4.6 from annotations
// in livestock/test/features/inventory/domain/usecases/register_product_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:livestock/features/inventory/domain/entities/product.dart'
    as _i2;
import 'package:livestock/features/inventory/domain/entities/product_category.dart'
    as _i7;
import 'package:livestock/features/inventory/domain/entities/sale_transaction.dart'
    as _i4;
import 'package:livestock/features/inventory/domain/entities/stock_transaction.dart'
    as _i3;
import 'package:livestock/features/inventory/domain/entities/stock_transaction_type.dart'
    as _i8;
import 'package:livestock/features/inventory/domain/repositories/inventory_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProduct_0 extends _i1.SmartFake implements _i2.Product {
  _FakeProduct_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStockTransaction_1 extends _i1.SmartFake
    implements _i3.StockTransaction {
  _FakeStockTransaction_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaleTransaction_2 extends _i1.SmartFake
    implements _i4.SaleTransaction {
  _FakeSaleTransaction_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i5.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Product> createProduct(_i2.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [product]),
            returnValue: _i6.Future<_i2.Product>.value(
              _FakeProduct_0(
                this,
                Invocation.method(#createProduct, [product]),
              ),
            ),
          )
          as _i6.Future<_i2.Product>);

  @override
  _i6.Future<_i2.Product> updateProduct(_i2.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i6.Future<_i2.Product>.value(
              _FakeProduct_0(
                this,
                Invocation.method(#updateProduct, [product]),
              ),
            ),
          )
          as _i6.Future<_i2.Product>);

  @override
  _i6.Future<_i2.Product?> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i6.Future<_i2.Product?>.value(),
          )
          as _i6.Future<_i2.Product?>);

  @override
  _i6.Future<List<_i2.Product>> getAllProducts({
    _i7.ProductCategory? category,
    bool? isLowStock,
    bool? isOutOfStock,
    bool? activeOnly = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, [], {
              #category: category,
              #isLowStock: isLowStock,
              #isOutOfStock: isOutOfStock,
              #activeOnly: activeOnly,
            }),
            returnValue: _i6.Future<List<_i2.Product>>.value(<_i2.Product>[]),
          )
          as _i6.Future<List<_i2.Product>>);

  @override
  _i6.Future<void> deactivateProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateProduct, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.StockTransaction> addStock({
    required String? productId,
    required double? quantity,
    String? reason,
    required String? performedBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addStock, [], {
              #productId: productId,
              #quantity: quantity,
              #reason: reason,
              #performedBy: performedBy,
            }),
            returnValue: _i6.Future<_i3.StockTransaction>.value(
              _FakeStockTransaction_1(
                this,
                Invocation.method(#addStock, [], {
                  #productId: productId,
                  #quantity: quantity,
                  #reason: reason,
                  #performedBy: performedBy,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.StockTransaction>);

  @override
  _i6.Future<_i3.StockTransaction> adjustStock({
    required String? productId,
    required double? newStock,
    required String? reason,
    required String? performedBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#adjustStock, [], {
              #productId: productId,
              #newStock: newStock,
              #reason: reason,
              #performedBy: performedBy,
            }),
            returnValue: _i6.Future<_i3.StockTransaction>.value(
              _FakeStockTransaction_1(
                this,
                Invocation.method(#adjustStock, [], {
                  #productId: productId,
                  #newStock: newStock,
                  #reason: reason,
                  #performedBy: performedBy,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.StockTransaction>);

  @override
  _i6.Future<_i4.SaleTransaction> recordSale({
    required String? productId,
    required double? quantity,
    required double? unitPrice,
    String? customerName,
    String? notes,
    required String? processedBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordSale, [], {
              #productId: productId,
              #quantity: quantity,
              #unitPrice: unitPrice,
              #customerName: customerName,
              #notes: notes,
              #processedBy: processedBy,
            }),
            returnValue: _i6.Future<_i4.SaleTransaction>.value(
              _FakeSaleTransaction_2(
                this,
                Invocation.method(#recordSale, [], {
                  #productId: productId,
                  #quantity: quantity,
                  #unitPrice: unitPrice,
                  #customerName: customerName,
                  #notes: notes,
                  #processedBy: processedBy,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.SaleTransaction>);

  @override
  _i6.Future<List<_i4.SaleTransaction>> getSales({
    DateTime? startDate,
    DateTime? endDate,
    String? productId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSales, [], {
              #startDate: startDate,
              #endDate: endDate,
              #productId: productId,
            }),
            returnValue: _i6.Future<List<_i4.SaleTransaction>>.value(
              <_i4.SaleTransaction>[],
            ),
          )
          as _i6.Future<List<_i4.SaleTransaction>>);

  @override
  _i6.Future<_i4.SaleTransaction?> getSaleById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSaleById, [id]),
            returnValue: _i6.Future<_i4.SaleTransaction?>.value(),
          )
          as _i6.Future<_i4.SaleTransaction?>);

  @override
  _i6.Future<List<_i3.StockTransaction>> getStockTransactions({
    required String? productId,
    _i8.StockTransactionType? type,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getStockTransactions, [], {
              #productId: productId,
              #type: type,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i6.Future<List<_i3.StockTransaction>>.value(
              <_i3.StockTransaction>[],
            ),
          )
          as _i6.Future<List<_i3.StockTransaction>>);

  @override
  _i6.Future<List<_i2.Product>> searchProducts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [query]),
            returnValue: _i6.Future<List<_i2.Product>>.value(<_i2.Product>[]),
          )
          as _i6.Future<List<_i2.Product>>);

  @override
  _i6.Future<List<_i2.Product>> getLowStockProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getLowStockProducts, []),
            returnValue: _i6.Future<List<_i2.Product>>.value(<_i2.Product>[]),
          )
          as _i6.Future<List<_i2.Product>>);

  @override
  _i6.Future<void> syncPendingTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingTransactions, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> hasPendingTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#hasPendingTransactions, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
